#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
rm -r log.*
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication extrudeMesh
runApplication topoSet
runApplication createPatch -overwrite
touch result.foam

#------------------------------------------------------------------------------
